### ISSUE TITLE
ステップ19: 複数人で利用できるようにしよう（ユーザの導入）

### ISSUE THREAD

**Issue by kihaya** [yumayo14/el-training#37]
ユーザモデルを作成してみましょう
+ 最初のユーザをseedで作成してみましょう
  + ユーザとタスクが紐づくようにしましょう
  + 関連に対してインデックスを貼りましょう
  + N+1問題を回避するための仕組みを取り入れましょう
+ ※ Herokuにデプロイした際に、すでに登録されているタスクとユーザが紐づいているようにしてください（データメンテナンス）

**Comment by yumayo14** [comment]
## Herokuでのデータメンテナンス

el-training yuma$ heroku maintenance:on

el-training yuma$ heroku run rails db:migrate

el-training yuma$ heroku run rails c

irb(main):001:0> User.create(name: '田中 宏和', accountid: 'tanahiro', password: 'Iamtestman')

irb(main):019:0> Task.all.each{ |task| task.update(dead_line_on: "2020-09-09", user: User.first) }

irb(main):022:0> Task.count
D, [2019-05-16T06:15:31.014561 #4] DEBUG -- :    (3.7ms)  SELECT COUNT(*) FROM `tasks`
=> 12

irb(main):024:0> Task.all.map{ |task| task.user }.count
---
=> 12

el-training yuma$ heroku maintenance:off

**Comment by yumayo14** [comment]
herokuでのデータメンテナンスが終わったので、お手隙でレビューお願いします。

**Comment by kihaya** [comment]
データ生成、データ更新をするときには`create!`、`update!`を使うといいですね。このままだとエラーになってもスルーしてしまうので。今回はOKです。
